### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by enaka24** [tobyxdd/notion-empty-trash#2]
I clicked the "empty trash" button but it said there was an error and to check the console for details.
![Screenshot 2024-04-07 191312](https://github.com/tobyxdd/notion-empty-trash/assets/105247193/906d0365-75ea-4f2c-ada6-ab8587f6d68f)

This is what the console shows. I have no idea what that means. How do I fix it so that it works?

**Comment by tobyxdd** [comment]
Could refresh/login again fix this error for you? Or maybe it's the same problem as this one? https://github.com/tobyxdd/notion-empty-trash/issues/1

**Comment by enaka24** [comment]
It's a private workspace but I relogged and it worked.
