### ISSUE TITLE
Work for my other two accounts, but doesn't work for this one [screenshot attached]

### ISSUE THREAD

**Issue by kristy-hu** [tobyxdd/notion-empty-trash#3]
Can you help identify the problem? 
Thanks a lot in advance!
![image](https://github.com/tobyxdd/notion-empty-trash/assets/58140450/0c65deb3-11af-4199-a70f-3eb28f87725f)

**Comment by kristy-hu** [comment]
Not sure if it's the underlying issue, but it may bring up some insights or ideas, or at least provide more context.

So here is the thing: 
Before the trash bin loads up, there is a few seconds of page showing it's empty until eventually everything is loaded.
![image](https://github.com/tobyxdd/notion-empty-trash/assets/58140450/9747a0d8-a3b2-41a9-a676-6a6c8cb03ad6)
Perhaps that's part of the issues? 
Thanks a lot in advance!

**Comment by tobyxdd** [comment]
There is a review that reports a similar problem and says it can be fixed by reordering the workspaces. Can you first confirm that it's the same problem?

https://chromewebstore.google.com/detail/notion-empty-trash/eajpmgfkkpbhafekaemjpapnnkejbblp/reviews

**Comment by tobyxdd** [comment]
> Perhaps that's part of the issues?

No, this shouldn't be the reason. My code makes its own API call to get trashed pages, it doesn't rely on what's shown on the pages.

**Comment by tobyxdd** [comment]
This should fix it. https://github.com/tobyxdd/notion-empty-trash/commit/de266eea5b504c762e5b4adb7786094b26bcb30e

**Comment by kristy-hu** [comment]
came up with this:
<img width="1440" alt="image" src="https://github.com/tobyxdd/notion-empty-trash/assets/58140450/8d13d497-1d85-4ec8-a959-b103ab579e42">
```javascript
Uncaught (in promise) HttpRequestError: Received HTTP 400
    at app-f2dbfa4ba0e0d14d.js:1:70546
    at async f (app-f2dbfa4ba0e0d14d.js:1:70138)
    at async V (219-810b0ad8146a0148.js:1:119251)
    at async Module.oe (search-651b7a9c3b4c09be.js:1:25215)
    at async 2498-dc2f0482c6cf8140.js:1:13146
```

**Comment by kristy-hu** [comment]
I think notion is currently updating their api, and the `deleteBlocks` may not work any more.
<img width="1440" alt="image" src="https://github.com/tobyxdd/notion-empty-trash/assets/58140450/0cac81d1-096f-4212-b5fd-e9a8075eae93">

**Comment by tobyxdd** [comment]
Try this https://github.com/tobyxdd/notion-empty-trash/commit/68e32f7414057b2e8f60f85ff7c7b18151dc23d2

**Comment by kristy-hu** [comment]
It works! Thank you so very much!!

**Comment by kristy-hu** [comment]
Issue closed.
